services:
  cf-blog-database:
    image: postgres:15.5
    container_name: ${APP_DATABASE_HOST}
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${APP_DB_NAME}
      POSTGRES_USER: ${APP_DB_USER}
      POSTGRES_PASSWORD: ${APP_DB_PASSWORD}
    ports:
      - ${APP_DATABASE_PORT}:5432
    networks:
      - network-cf-blog
    volumes:
      - database-cf-blog:/var/lib/postgresql/data

  cf-blog-backend:
    image: cf-blog-backend:0.0.3
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    working_dir: /app-backend
    container_name: ${APP_BACKEND_HOST}
    restart: unless-stopped
    env_file:
      - ./.env
      - ./backend/.env.docker.production.sample
    environment:
      - NODE_ENV=production
    depends_on:
      - cf-blog-database
    ports:
      - 82:80
      - 4432:443
    networks:
      - network-cf-blog
    volumes:
      - ./backend:/app-backend

  cf-blog-frontend:
    image: cf-blog-frontend:0.0.3
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    working_dir: /app-frontend
    container_name: ${APP_FRONTEND_HOST}
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
    depends_on:
      - cf-blog-backend
    ports:
      - 81:80
      - 4431:443
    networks:
      - network-cf-blog
    volumes:
      - ./frontend:/app-frontend
      #- ./frontend/default.pem:/etc/ssl/default.pem
      #- ./frontend/default.key:/etc/ssl/default.key

  cf-blog-reverse-proxy:
    image: cf-blog-reverse-proxy:0.0.3
    build:
      context: ./reverse-proxy
      dockerfile: Dockerfile.prod
    working_dir: /etc/nginx
    container_name: ${APP_PROXY_HOST}
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
    depends_on:
      - cf-blog-backend
      - cf-blog-frontend
    ports:
      - ${APP_PROD_HTTP_PORT}:80
      - ${APP_PROD_HTTPS_PORT}:443
    networks:
      - network-cf-blog
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
      #- ./reverse-proxy/default.pem:/etc/ssl/default.pem
      #- ./reverse-proxy/default.key:/etc/ssl/default.key

networks:
  network-cf-blog:

volumes:
  database-cf-blog:
    driver: local