services:
  cf-blog-database:
    image: postgres:15.5
    container_name: ${APP_DATABASE_HOST}
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      NODE_ENV: development
    environment:
      POSTGRES_DB: ${APP_DB_NAME}
      POSTGRES_USER: ${APP_DB_USER}
      POSTGRES_PASSWORD: ${APP_DB_PASSWORD}
    ports:
      - ${APP_DATABASE_PORT}:5432
    networks:
      - network-cf-blog
    volumes:
      - database-cf-blog:/var/lib/postgresql/data
      - ./db/sample_data.sql:/docker-entrypoint-initdb.d/init.sql

  cf-blog-backend:
    image: cf-blog-backend:0.0.3
    build: ./backend
    working_dir: /backend
    container_name: ${APP_BACKEND_HOST}
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      NODE_ENV: development
    depends_on:
      - cf-blog-database
    ports:
      - ${APP_BACKEND_PORT}:3001
    networks:
      - network-cf-blog
    volumes:
      - ./backend:/app-backend

  cf-blog-frontend:
    image: cf-blog-frontend:0.0.3
    build: ./frontend
    working_dir: /app-frontend
    container_name: ${APP_FRONTEND_HOST}
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      NODE_ENV: development
    depends_on:
      - cf-blog-backend
    ports:
      - ${APP_FRONTEND_PORT}:3000
    networks:
      - network-cf-blog
    volumes:
      - ./frontend:/app-frontend

networks:
  network-cf-blog:
  
volumes:
  database-cf-blog:
    driver: local