services:
  cf-blog-database:
    image: postgres:15.5
    container_name: ${APP_DB_HOST}
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${APP_DB_NAME}
      POSTGRES_USER: ${APP_DB_USER}
      POSTGRES_PASSWORD: ${APP_DB_PASSWORD}
    ports:
      - ${APP_DB_PORT}:5432
    networks:
      - network-cf-blog
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  cf-blog-backend:
    image: cf-blog-backend:0.0.3
    build: ./backend
    working_dir: /app-backend
    container_name: ${APP_BACKEND_HOST}
    restart: unless-stopped
    env_file:
      - ./.env
    depends_on:
      - cf-blog-database
    ports:
      - ${APP_BACKEND_PORT}:3001
    networks:
      - network-cf-blog
    volumes:
      - .:/app-build

  cf-blog-frontend:
    image: cf-blog-frontend:0.0.3
    build: ./frontend
    working_dir: /app-frontend
    container_name: ${APP_FRONTEND_HOST}
    restart: unless-stopped
    env_file:
      - ./.env
    depends_on:
      - cf-blog-backend
    ports:
      - ${APP_FRONTEND_PORT}:3000
      - ${APP_FRONTEND_PROD_PORT}:80
    networks:
      - network-cf-blog
    volumes:
      - .:/app-build
      - ./nginx.conf:/etc/nginx/nginx.conf

networks:
  network-cf-blog: