services:
  cf-blog-database-dev:
    image: postgres:15.5
    container_name: ${APP_DATABASE_HOST}-dev
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${APP_DB_NAME}
      POSTGRES_USER: ${APP_DB_USER}
      POSTGRES_PASSWORD: ${APP_DB_PASSWORD}
    ports:
      - ${APP_DATABASE_PORT}:5432
    networks:
      - network-cf-blog-dev
    volumes:
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - database-cf-blog-dev:/var/lib/postgresql/data

  cf-blog-backend-dev:
    image: gsmx64/cf-blog-backend-dev:${APP_BUILD_NUMBER}
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: ${APP_BACKEND_HOST}-dev
    restart: unless-stopped
    env_file:
      - ./.env
      - ./backend/.env.development
    environment:
      - NODE_ENV=development
    depends_on:
      - cf-blog-database-dev
    ports:
      - ${APP_BACKEND_PORT}:3001
    networks:
      - network-cf-blog-dev
    volumes:
      - ./backend:/app-backend
      - ./node_modules:/app-backend/node_modules

  cf-blog-frontend-dev:
    image: gsmx64/cf-blog-frontend-dev:${APP_BUILD_NUMBER}
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: ${APP_FRONTEND_HOST}-dev
    restart: unless-stopped
    env_file:
      - ./.env
      - ./frontend/.env.development
    environment:
      - NODE_ENV=development
    depends_on:
      - cf-blog-backend-dev
    ports:
      - ${APP_FRONTEND_PORT}:3000
    networks:
      - network-cf-blog-dev
    volumes:
      - ./frontend:/app-frontend
      - ./node_modules:/app-frontend/node_modules

networks:
  network-cf-blog-dev:
  
volumes:
  database-cf-blog-dev:
    driver: local