version: '3.9'

services:
  cf-blog-database:
    image: postgres:15.5
    container_name: ${APP_DB_HOST}
    restart: always
    env_file:
      - ./.env
      - ./backend/.env.development
    environment:
      POSTGRES_DB: ${APP_DB_NAME}
      POSTGRES_USER: ${APP_DB_USER}
      POSTGRES_PASSWORD: ${APP_DB_PASSWORD}
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - ${APP_DB_PORT}:5432

  cf-blog-backend:
    image: cf-blog-backend:0.0.1
	build: ./backend
	container_name: ${APP_BACKEND_HOST}
	restart: unless-stopped
    env_file:
      - ./.env
      - ./backend/.env.development
    depends_on:
      - cf-blog-database
    ports:
      - ${APP_BACKEND_PORT}:3001
    
    volumes:
      - .:/application
      - ./node_modules:/application/node_modules

  frontend:
    image: cf-blog-frontend:0.0.1
	build: ./frontend
	container_name: ${APP_FRONTEND_HOST}
    restart: unless-stopped
	env_file:
      - ./.env
      - ./frontend/.env.development
    depends_on:
      - cf-blog-backend
    ports:
      - ${APP_FRONTEND_PORT}:3000
      - ${APP_FRONTEND_PROD_PORT}:80
    volumes:
      - .:/application
      - ./node_modules:/application/node_modules
      - ./nginx.conf:/etc/nginx/nginx.conf

