services:

  cf-blog-backend:
    image: gsmx64/cf-blog-backend:${APP_BUILD_NUMBER}
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: ${DOCKER_BACKEND_HOST}
    restart: unless-stopped
    env_file:
      - ./backend/.env.production
    environment:
      - NODE_ENV=production
    ports:
      - ${DOCKER_BACKEND_PORT}:${APP_BACKEND_PORT}
    networks:
      - network-cf-blog
    volumes:
      - ./node_modules:/home/app/node_modules

  cf-blog-frontend:
    image: gsmx64/cf-blog-frontend:${APP_BUILD_NUMBER}
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: ${DOCKER_FRONTEND_HOST}
    restart: unless-stopped
    env_file:
      - ./frontend/.env.production
    environment:
      - NODE_ENV=production
    depends_on:
      - cf-blog-backend
    ports:
      - ${DOCKER_FRONTEND_PORT}:${APP_FRONTEND_PORT}
    networks:
      - network-cf-blog
    volumes:
      - ./frontend/nginx.default.conf:/etc/nginx/conf.d/default.conf
      #- ./frontend/default.pem:/etc/ssl/default.pem
      #- ./frontend/default.key:/etc/ssl/default.key

  cf-blog-reverse-proxy:
    image: gsmx64/cf-blog-reverse-proxy:${APP_BUILD_NUMBER}
    build:
      context: ./reverse-proxy
      dockerfile: Dockerfile.prod
    container_name: ${DOCKER_PROXY_HOST}
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
    depends_on:
      - cf-blog-backend
      - cf-blog-frontend
    ports:
      - ${DOCKER_APP_HTTP_PORT}:${DOCKER_APP_HTTP_PORT}
      - ${DOCKER_APP_HTTPS_PORT}:${DOCKER_APP_HTTPS_PORT}
    networks:
      - network-cf-blog
    volumes:
      - ./reverse-proxy/templates:/etc/nginx/templates
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
      #- ./reverse-proxy/default.pem:/etc/ssl/default.pem
      #- ./reverse-proxy/default.key:/etc/ssl/default.key

networks:
  network-cf-blog:
