services:
  cf-blog-database-dev:
    image: postgres:15.5
    container_name: ${DOCKER_DATABASE_HOST}-dev
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      PGPORT: ${APP_DB_PORT}
      POSTGRES_DB: ${APP_DB_NAME}
      POSTGRES_USER: ${APP_DB_USER}
      POSTGRES_PASSWORD: ${APP_DB_PASSWORD}
    ports:
      - ${DOCKER_DATABASE_PORT}:${APP_DB_PORT}
    networks:
      - network-cf-blog-dev
    volumes:
      - database-cf-blog-dev:/var/lib/postgresql/data

  cf-blog-backend-dev:
    image: gsmx64/cf-blog-backend-dev:${APP_BUILD_NUMBER}
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: ${DOCKER_BACKEND_HOST}-dev
    restart: unless-stopped
    env_file:
      - ./.env
      - ./backend/.env.development
    environment:
      - NODE_ENV=development
    depends_on:
      - cf-blog-database-dev
    ports:
      - ${DOCKER_BACKEND_DEV_PORT}:${APP_BACKEND_DEV_PORT}
    networks:
      - network-cf-blog-dev
    volumes:
      - ./backend:/app-backend
      - ./node_modules:/app-backend/node_modules

  cf-blog-frontend-dev:
    image: gsmx64/cf-blog-frontend-dev:${APP_BUILD_NUMBER}
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: ${DOCKER_FRONTEND_HOST}-dev
    restart: unless-stopped
    env_file:
      - ./.env
      - ./frontend/.env.development
    environment:
      - NODE_ENV=development
    depends_on:
      - cf-blog-backend-dev
    ports:
      - ${DOCKER_FRONTEND_DEV_PORT}:${APP_FRONTEND_DEV_PORT}
    networks:
      - network-cf-blog-dev
    volumes:
      - ./frontend:/app-frontend
      - ./node_modules:/app-frontend/node_modules

networks:
  network-cf-blog-dev:
  
volumes:
  database-cf-blog-dev:
    driver: local