version: '3.1'

services:
  db:
    image: postgres:15.5
    container_name: cf-blog-db_pg
    restart: always
    env_file:
      - ./backend/.env
      - ./backend/.development.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - ${APP_DB_PORT}:5432

  backend:
    container_name: cf-blog-backend
    env_file:
      - ./backend/.env
      - ./backend/.development.env
    command: npm run start:dev
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - ${APP_PORT}:3001
    restart: always
    volumes:
      - .:/application
      - ./node_modules:/application/node_modules

  frontend:
    container_name: cf-blog-frontend
    env_file:
      - ./frontend/.env
      - ./frontend/.development.env
    command: npm run start:dev
    depends_on:
      - backend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - ${APP_PORT}:3000
    restart: always
    volumes:
      - .:/application
      - ./node_modules:/application/node_modules