version: '3.1'

services:
  db:
    image: postgres:15.5
    container_name: blogdb_pg
    restart: always
    env_file:
      - .env
      - .development.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - ${DB_PORT}:5432