FROM node:20.14-alpine

WORKDIR /app-backend

RUN apk update && apk add build-base

COPY package*.json /

RUN npm i

COPY . .

RUN cp .env.docker.development.sample .env.development

EXPOSE 3001

CMD ["npm", "run", "start:dev"]