FROM node:20.14-alpine

WORKDIR /app-backend

RUN apk update && apk add build-base

COPY . .

RUN cp .env.docker.${NODE_ENV}.sample .env.${NODE_ENV}

RUN npm i

EXPOSE 3001

CMD ["npm", "run", "start:dev"]