FROM node:20.14-alpine

WORKDIR /app-backend

RUN apk update && apk add build-base

COPY package*.json /

RUN npm i

RUN addgroup -S app && adduser -S app -G app

COPY ./ /

#USER app  //NOSONAR

EXPOSE 3001

CMD ["npm", "run", "start:dev"]